# This is an example config file that only sets the default values for each value.
# Configure your own desired options before using

# The `layman` section configures options that apply to the layman daemon, and any fallback
# values for options not set in a [workspace] or [output] section.
[layman]
defaultLayout = "none"	# The default WLM to assign to a workspace
excludedWorkspaces = []	# Numbers of workspaces to be excuded
excludedOutputs = []	# Names of outputs to be excuded
debug = false			# Enable logging debug messages globaly
depthLimit = 0 # Autotiling: Default depth limit (disabled) for all workspaces
stackLayout = "splitv"	# MasterStack: Default stack layout for all workspaces
masterWidth = 50		# MasterStack: Default master width for all workspaces


# `output` sections configure options for workspaces created on this output.
[output.DP-1]
defaultLayout = "none"	# The default WLM to assign to a workspace on this output
debug = false			# Enable debug messages for WLMs on this output
depthLimit = 0 # Autotiling: Depth limit (disabled) for workspaces on this output
stackLayout = "splitv"	# MasterStack: Default stack layout for workspaces on this output
masterWidth = 50		# MasterStack: Default master width for workspaces on this output


# `workspace` sections configure options for the specified workspace.
[workspace.1]
defaultLayout = "none"	# The default WLM to assign to this workspace
debug = false			# Enable debug messages for this workspace
depthLimit = 0 # Autotiling: Depth limit (disabled) for this workspace
stackLayout = "splitv"	# MasterStack: Stack layout for this workspace
masterWidth = 50		# MasterStack: Master width for this workspaces on this output

